name: Actions

on: [push]

jobs:
  lint:
    name: lint
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: v1-yarn-deps-${{ hashFiles('**/yarn.lock') }}
          restore-keys: v1-yarn-deps-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --production=false --frozen-lockfile

      - name: Run eslint
        run: yarn lint

      - name: Run prettier
        run: yarn check-format

  test:
    name: test
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    container:
      image: node:16.12

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: v1-yarn-deps-${{ hashFiles('**/yarn.lock') }}
          restore-keys: v1-yarn-deps-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --production=false --frozen-lockfile

      - name: test
        run: yarn test

  build:
    name: build
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    container:
      image: node:16.12

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: v1-yarn-deps-${{ hashFiles('**/yarn.lock') }}
          restore-keys: v1-yarn-deps-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --production=false --frozen-lockfile

      - name: Build
        id: build
        run: yarn build

  deploy:
    name: deploy
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      user_name: 'CampbellDocherty'
      user_email: 'campbellsofitsidocherty@gmail.com'
      github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
      repository: ${{ github.repository }}
    container:
      image: node:16.12

    steps:
      - name: deploy
        run: |
          git config --global user.name ${{ env.user_name }}
          git config --global user.email ${{ env.user_email }}
          git remote set-url origin https://${{ env.github_token }}@github.com/${{ env.repository }}
          yarn deploy
